### ISSUE TITLE
How to send this signal?

### ISSUE THREAD

**Issue by probonopd** [bskari/pi-rc#21]
I am trying to send [this](https://gist.github.com/probonopd/c114ea42ea6fef5b6b6b6118ae49ebf8) signal, with "+" being "27.145 MHz on", and "-" = off/other frequency:

`+9024 -4512 +564 -564 +564 -1692 +564 -564 +564 -1692 +564 -1692 +564 -1692 +564 -564 +564 -1692 +564 -1692 +564 -564 +564 -1692 +564 -564 +564 -1692 +564 -564 +564 -1692 +564 -564 +564 -1692 +564 -564 +564 -564 +564 -564 +564 -564 +564 -564 +564 -564 +564 -564 +564 -564 +564 -1692 +564 -1692 +564 -1692 +564 -1692 +564 -1692 +564 -1692 +564 -1692 +564 -38628`

I translated the above to

```
[
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 9024,
        "spacing_us": 4512,
        "repeats": 1
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 564,
        "repeats": 1
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 1692,
        "repeats": 1
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 564,
        "repeats": 1
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 1692,
        "repeats": 3
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 564,
        "repeats": 1
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 1692,
        "repeats": 2
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 564,
        "repeats": 1
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 1692,
        "repeats": 1
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 564,
        "repeats": 1
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 1692,
        "repeats": 1
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 564,
        "repeats": 1
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 1692,
        "repeats": 1
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 564,
        "repeats": 1
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 1692,
        "repeats": 1
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 564,
        "repeats": 8
    },
    {
        "frequency": 27.145,
        "dead_frequency": 49.830,
        "burst_us": 564,
        "spacing_us": 1692,
        "repeats": 8
    }
]
```

But when trying to send it, I get:

```
pi@raspberrypi:~$ python pi-rc-master/interactive_control.py mute.json 
Traceback (most recent call last):
  File "pi-rc-master/interactive_control.py", line 211, in <module>
    main()
  File "pi-rc-master/interactive_control.py", line 199, in main
    configuration = load_configuration(configuration_file)
  File "pi-rc-master/interactive_control.py", line 24, in load_configuration
    dead = dead_frequency(configuration['frequency'])
TypeError: list indices must be integers, not str
```

What am I doing wrong?

**Comment by probonopd** [comment]
To be clear, I just want to send the signal once without repeats.

**Comment by probonopd** [comment]
I see, `cat mute.json > /dev/udp/127.0.0.1/12345` - probably this should be mentioned in the documentation...

**Comment by RobertBush** [comment]
what does the line like this: (from the baja-extreme.json configuration file) 

"frequency": 49.83,
 
in your configuration file look like?

**Comment by probonopd** [comment]
```
"frequency": 27.145,
```

**Comment by probonopd** [comment]
Updated the original post.

**Comment by bskari** [comment]
Hello, I looked through your gist. Looks like a cool project! I think that gqrx can record samples to IQ files (under the tools menu), and you could use [rpitx](https://github.com/F5OEO/rpitx) to replay that IQ file once on a Raspberry Pi. My repository here is more set up for broadcasting signals repeatedly for radio control stuff, and rpitx is the better choice for broadcasting single signals. rpitx also supports FT files, which I _think_ you could convert the above signal specification into, although I don't know how to do it off hand.
